name: ml_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.15
  - numpy=1.26.4
  - pandas=1.4.3
  - scikit-learn=1.1.1
  - scipy=1.8.1
  - matplotlib=3.5.2
  - ipykernel=6.29.5
  - jupyterlab=4.2.5
  - tensorflow=2.17.0
  - pytorch=2.3.0
  - torchvision=0.18.1
  - tensorboard=2.17.1
  - keras=3.5.0
  - seaborn=0.11.2
  - pip
  - pip:
    - absl-py==2.1.0
    - asttokens==2.0.5
    - beautifulsoup4==4.12.3
    - bleach==4.1.0
    - chardet==4.0.0
    - cython==3.0.10
    - defusedxml==0.7.1
    - fonttools==4.34.4
    - grpcio==1.66.1
    - h5py==3.11.0
    - ipython==8.27.0
    - jinja2==3.1.4
    - joblib==1.1.0
    - keras==3.5.0
    - lightgbm==3.3.2
    - ml-dtypes==0.4.1
    - numpy-base==1.26.4
    - opt-einsum==3.3.0
    - pandas==1.4.3
    - pillow==9.2.0
    - protobuf==4.25.4
    - psutil==5.9.0
    - pytorch-cpu==2.3.0
    - pyyaml==6.0.2
    - scikit-learn==1.1.1
    - scipy==1.8.1
    - tensorboard-data-server==0.7.2
    - tensorflow-io-gcs-filesystem==0.37.1
    - tqdm==4.64.0
    - wheel==0.44.0
  - pip:
    - lxml==4.9.3
    - requests==2.32.3
    - yaml==0.2.5
  - conda:
    - pip
    - pyzmq
    - libgfortran-ng
    - libomp
    - libprotobuf
    - libomp
    - libgcc-ng
    - libopenblas
    - zlib
    - libiconv
    - xz
    - cudatoolkit=11.3
  - conda:
    - opencv=4.5.2
    - tensorflow
    - numba
    - zlib
    - lz4-c
    - pcre2
  - conda-forge:
    - matplotlib-inline
    - jupyter-client
    - jupyter-server
